#!/usr/bin/env python3
"""
Theme Switch Script Example
----------------------------
This script demonstrates how an AI agent (or user) could apply a theme
to all relevant config files at once, using the palette from the MCP server.
"""

import argparse
from pathlib import Path

DEFAULT_COLORS = {
    "catppuccin": {
        "base": "#1e1e2e",
        "surface": "#313244",
        "text": "#cdd6f4",
        "accent": "#89b4fa",
        "secondary": "#cba6f7",
        "error": "#f38ba8",
        "success": "#a6e3a1",
        "warning": "#fab387",
    },
    "tokyo-night": {
        "base": "#1a1b26",
        "surface": "#24283b",
        "text": "#a9b1d6",
        "accent": "#7aa2f7",
        "secondary": "#bb9af7",
        "error": "#f7768e",
        "success": "#9ece6a",
        "warning": "#e0af68",
    },
    "modern-glass": {
        "base": "#1e1e2e",
        "surface": "#313244",
        "text": "#cdd6f4",
        "accent": "#89b4fa",
        "secondary": "#cba6f7",
        "error": "#f38ba8",
        "success": "#a6e3a1",
        "warning": "#fab387",
    },
}


def apply_theme(name: str, target_dir: Path):
    colors = DEFAULT_COLORS.get(name, DEFAULT_COLORS["catppuccin"])
    print(f"Applying theme: {name}")
    print(f"Colors: {colors}")

    # Example: Update a placeholder config file with theme colors
    target_dir.mkdir(parents=True, exist_ok=True)
    theme_file = target_dir / f"theme_{name}.conf"
    content = f"# Theme: {name}\n# Auto-generated by theme script\n"
    for k, v in colors.items():
        content += f"# color_{k} = {v}\n"
    theme_file.write_text(content)
    print(f"Theme config written to: {theme_file.absolute()}")
    print("In a full setup, this script would update:")
    print("  - ~/.config/hypr/hyprland.conf  (border colors, decoration)")
    print("  - ~/.config/waybar/style.css   (background, module colors)")
    print("  - ~/.config/hypr/scripts/theme.sh")
    print("  - Any terminal / rofi / notification configs")
    return colors


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Switch themes for Hyprland setup")
    parser.add_argument("theme", choices=DEFAULT_COLORS.keys(), help="Theme name")
    parser.add_argument("--dir", default=str(Path.home() / ".config" / "hypr"), help="Target config directory")
    args = parser.parse_args()
    apply_theme(args.theme, Path(args.dir))
